os: linux
dist: xenial

language: nodejs
node_js:
  - stable

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "jangarstud" # the key of the org you chose at step #3
    token: $SONAR_TOKEN # encrypted value of your token

script:
  - npm install -g @vue/cli
  - npm install
  - npm run test:unit
  - sonar-scanner

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: main

notifications:
  slack: ull-sytw2020-e09:CGvvKj8wLLQ1WpURL8IGYBdy
